// projects.js – Data project untuk halaman Project Demo
const projects = [
  {
    id: 1,
    title: "NextStep",
    category: "web",
    icon: "fa-solid fa-briefcase",
    iconColor: "#4f9cf9",
    tags: ["React", "AI", "Career"],
    description: "The smart path to your future career.",
    detail: "Platform rekomendasi karir adaptif yang didukung analisis CV dan tren pasar kerja menggunakan kecerdasan buatan. NextStep membantu pengguna menemukan jalur karir terbaik berdasarkan skill dan pengalaman mereka.",
    tech: ["React", "Node.js", "AI/ML", "REST API"],
    link: "https://fnl-fe-nextstep-34zn.vercel.app/",
    github: null,
    year: "2024"
  },
  {
    id: 2,
    title: "Tugas 1 Pemrograman Web",
    category: "web",
    icon: "fa-brands fa-html5",
    iconColor: "#e34c26",
    tags: ["HTML", "CSS"],
    description: "Halaman web sederhana menggunakan HTML dan CSS.",
    detail: "Tugas pertama mata kuliah Pemrograman Web yang berisi tentang pembuatan halaman web sederhana menggunakan HTML dan CSS. Fokus pada struktur semantik dan styling dasar.",
    tech: ["HTML5", "CSS3"],
    link: "https://feuriee.github.io/Tugas-1-Praktikum-Pemrograman-Web-/",
    github: "https://github.com/Feuriee/Tugas-1-Praktikum-Pemrograman-Web-",
    year: "2024"
  },
  {
    id: 3,
    title: "Tugas 2 Pemrograman Web",
    category: "web",
    icon: "fa-brands fa-js",
    iconColor: "#f7df1e",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "Halaman web responsif menggunakan HTML, CSS, dan JavaScript.",
    detail: "Tugas kedua mata kuliah Pemrograman Web yang memperkenalkan konsep desain responsif dan interaktivitas menggunakan JavaScript. Termasuk layouting, media queries, dan manipulasi DOM.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    link: "https://feuriee.github.io/Tugas-2-Praktikum-Pemrograman-Web/",
    github: "https://github.com/Feuriee/Tugas-2-Praktikum-Pemrograman-Web",
    year: "2024"
  },
  {
    id: 4,
    title: "Tugas 3 Pemrograman Web",
    category: "web",
    icon: "fa-solid fa-list-check",
    iconColor: "#22c55e",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "Aplikasi To Do List menggunakan HTML, CSS, dan JavaScript.",
    detail: "Tugas ketiga mata kuliah Pemrograman Web berupa aplikasi To Do List interaktif. Fitur meliputi tambah, hapus, dan tandai selesai tugas, dengan penyimpanan data menggunakan localStorage.",
    tech: ["HTML5", "CSS3", "JavaScript", "localStorage"],
    link: "https://feuriee.github.io/Tugas-3-Praktikum-Pemrograman-Web/",
    github: "https://github.com/Feuriee/Tugas-3-Praktikum-Pemrograman-Web",
    year: "2024"
  },
  {
    id: 5,
    title: "TrainKu App",
    category: "mobile",
    icon: "fa-solid fa-train",
    iconColor: "#f59e0b",
    tags: ["React Native", "Mobile", "Expo"],
    description: "Aplikasi booking tiket kereta berbasis React Native.",
    detail: "Aplikasi mobile untuk pemesanan tiket kereta api yang dibangun menggunakan React Native dan Expo. Fitur meliputi pencarian rute, pemesanan tiket, dan manajemen profil pengguna.\n\n🔑 Demo login:\n• Admin: email: admin | password: TrainKu\n• User: email: user | password: user123",
    tech: ["React Native", "Expo", "REST API"],
    link: "https://trainku--b3nua4mqav.expo.app/",
    github: null,
    year: "2024"
  },
  {
    id: 6,
    title: "FindYourAnime App",
    category: "mobile",
    icon: "fa-solid fa-tv",
    iconColor: "#ec4899",
    tags: ["React Native", "Mobile", "API"],
    description: "Aplikasi pencarian anime berbasis React Native.",
    detail: "Aplikasi mobile untuk mencari dan menemukan informasi anime menggunakan React Native dan Expo. Terhubung ke API anime untuk mendapatkan data real-time termasuk rating, sinopsis, dan episode.",
    tech: ["React Native", "Expo", "Anime API"],
    link: "https://findyouranime--i87punoi21.expo.app/",
    github: null,
    year: "2024"
  },
  {
    id: 7,
    title: "Game TikTakToe",
    category: "game",
    icon: "fa-solid fa-gamepad",
    iconColor: "#a78bfa",
    tags: ["Java", "Game", "Desktop"],
    description: "Permainan TikTakToe sederhana menggunakan Java.",
    detail: "Game Tic-Tac-Toe klasik yang diimplementasikan menggunakan bahasa pemrograman Java dengan antarmuka grafis. Mendukung mode dua pemain dan dilengkapi dengan logika pengecekan pemenang secara otomatis.",
    tech: ["Java", "Swing/AWT"],
    link: "https://github.com/Feuriee/TikTakToe",
    github: "https://github.com/Feuriee/TikTakToe",
    year: "2024"
  }
];
